name: CI Workflow

on:
  push:
    branches:
      - main  # 必要に応じてブランチを変更
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # 最新の main ブランチを取得
          fetch-depth: 0  # すべての履歴を取得

      - name: Check latest commit
        run: git log -1
